/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class EditDaftarNama extends javax.swing.JFrame {
    public int nomorUrut;
    public String user = " ";
    ArrayList<String> dataNama = new ArrayList<>();
    /**
     * Creates new form EditDaftarNama
     */
    public EditDaftarNama() {
        setSize(550, 600);
        setLocationRelativeTo(null);
        initComponents();
    }

    public void tampilkanDariDB() {
        txaDaftarNama.setText("");
        dataNama.stream().forEach((a) -> {
            nomorUrut++;
            txaDaftarNama.append(nomorUrut + ". " + a + "\n");
        });
            
        txfNama.setText("");
        lbJmlNama.setText((dataNama.size()) + "");
    }
    
    public void addNama(){
        
        String nama = txfNama.getText();
        if("".equals(nama)){
            JOptionPane.showMessageDialog(this, "Masukan nama !");
        }else{
            dataNama.add(nama);
            /*
            if (nomorUrut == 3) {
                dataNama.remove(1);
            }*/
            nomorUrut = 0;
            txaDaftarNama.setText("");
            dataNama.stream().forEach((a) -> {
                nomorUrut++;
                txaDaftarNama.append(nomorUrut + ". " + a + "\n");
            });
            
            txfNama.setText("");
            lbJmlNama.setText((dataNama.size()) + "");
        }
    }
   
    public void hapusSatuNama(){
        if (Integer.parseInt(txfHapusSatu.getText()) >= 1 && Integer.parseInt(txfHapusSatu.getText()) <= dataNama.size()) {
            txaDaftarNama.setText("");
            dataNama.remove(Integer.parseInt(txfHapusSatu.getText()) - 1);
            nomorUrut = 0;
            dataNama.stream().forEach((a) -> {
                    nomorUrut++;
                    txaDaftarNama.append(nomorUrut + ". " + a + "\n");
            });
        
        lbJmlNama.setText(Integer.toString(dataNama.size()));
        } else {
            JOptionPane.showMessageDialog(this, "Harap masukkan nomor yang ada di daftar nama");
        }
    } 
                    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelInpNama = new javax.swing.JLabel();
        txfNama = new javax.swing.JTextField();
        btnNama = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txfHapusSatu = new javax.swing.JTextField();
        btnNama1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        btnNama2 = new javax.swing.JButton();
        toGenerator = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDaftarNama = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        lbJmlNama = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setText("Edit Daftar Nama");

        jButton11.setBackground(new java.awt.Color(255, 255, 0));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/output-onlinepngtools (4).png"))); // NOI18N
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));

        labelInpNama.setText("Nama anggota :");

        txfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNamaActionPerformed(evt);
            }
        });

        btnNama.setBackground(new java.awt.Color(255, 102, 0));
        btnNama.setText("Tambahkan");
        btnNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNamaActionPerformed(evt);
            }
        });

        jLabel2.setText("Hapus nama urutan ke :");

        txfHapusSatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfHapusSatuActionPerformed(evt);
            }
        });

        btnNama1.setBackground(new java.awt.Color(255, 102, 0));
        btnNama1.setText("Hapus");
        btnNama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNama1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Judul daftar nama :");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        btnNama2.setBackground(new java.awt.Color(255, 102, 0));
        btnNama2.setText("Simpan Daftar");
        btnNama2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNama2ActionPerformed(evt);
            }
        });

        toGenerator.setBackground(new java.awt.Color(255, 102, 0));
        toGenerator.setText("Masuk ke menu pengacakan");
        toGenerator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toGeneratorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(toGenerator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(labelInpNama)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txfNama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfHapusSatu)
                            .addComponent(jTextField2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNama1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNama2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNama))
                    .addComponent(labelInpNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txfHapusSatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNama1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNama2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toGenerator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        txaDaftarNama.setColumns(20);
        txaDaftarNama.setRows(5);
        jScrollPane1.setViewportView(txaDaftarNama);

        jLabel4.setText("Jumlah nama :");

        lbJmlNama.setText("0");

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setText("Kosongkan Daftar Nama");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbJmlNama)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jButton1)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbJmlNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        HalamanUtama h = new HalamanUtama();
        h.user = this.user;
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void txfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNamaActionPerformed
        addNama();        
    }//GEN-LAST:event_txfNamaActionPerformed

    private void btnNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNamaActionPerformed
        addNama();        
    }//GEN-LAST:event_btnNamaActionPerformed

    private void txfHapusSatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfHapusSatuActionPerformed
        hapusSatuNama();
    }//GEN-LAST:event_txfHapusSatuActionPerformed

    private void btnHapusSatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusSatuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusSatuActionPerformed

    private void txfJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfJudulActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnMulaiAcakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulaiAcakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMulaiAcakActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dataNama.removeAll(dataNama);
        txaDaftarNama.setText("");
        lbJmlNama.setText("0");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void toGeneratorActionPerformed(java.awt.event.ActionEvent evt) {
        if (this.dataNama.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harap mengisi daftar nama terlebih dahulu");
        } else {
            Generator g = new Generator();
            g.user = this.user;
            g.setVisible(true);
            this.dispose();
            g.dataNama.addAll(this.dataNama);
        }
    }
    
    private void btnNama1ActionPerformed(java.awt.event.ActionEvent evt) {
        hapusSatuNama();
    }
    
    private void btnNama2ActionPerformed(java.awt.event.ActionEvent evt) {
        if (dataNama.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data nama kosong, tidak dapat menyimpan");
        }else if (jTextField2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap mengisi judul daftar nama terlebih dahulu");
        }else {
            try{
                String dataNamaString = String.join(",", dataNama);
                String sql = "SELECT MAX(id_daftar) FROM daftar_nama";
                java.sql.Connection conn = (Connection)Config.configDB();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);
                res.next();
                int saveID = res.getInt(1)+1;

                sql = "SELECT MAX(urutan_daftar) FROM daftar_nama WHERE username = '" + user + "'";
                java.sql.Statement stmUrutanData = conn.createStatement();
                java.sql.ResultSet resUrutanData = stmUrutanData.executeQuery(sql);
                resUrutanData.next();
                int urutanSave = resUrutanData.getInt(1)+1;
                   
                sql = "INSERT INTO daftar_nama VAlUES ('" + saveID + "','" + jTextField2.getText() + "','" + dataNamaString + "','" + urutanSave + "','" + user + "')";
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(null, "Proses Simpan Data Berhasil!");
            }catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }
    
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
        if (dataNama.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data nama kosong, tidak dapat menyimpan!");
        }else if (jTextField2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap mengisi judul daftar nama terlebih dahulu");
        }else {
            try{
                String dataNamaString = String.join(",", dataNama);
                String sql = "SELECT MAX(id_daftar) FROM daftar_nama";
                java.sql.Connection conn = (Connection)Config.configDB();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);
                res.next();
                int saveID = res.getInt(1)+1;

                sql = "SELECT MAX(urutan_daftar) FROM daftar_nama WHERE username = '" + user + "'";
                java.sql.Statement stmUrutanData = conn.createStatement();
                java.sql.ResultSet resUrutanData = stmUrutanData.executeQuery(sql);
                resUrutanData.next();
                int urutanSave = resUrutanData.getInt(1)+1;

                sql = "INSERT INTO daftar_nama VAlUES ('" + saveID + "','" + jTextField2.getText() + "','" + dataNamaString + "','" + urutanSave + "','" + user + "')";
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(null, "Proses Simpan Data Berhasil!");
            }catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDaftarNama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDaftarNama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDaftarNama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDaftarNama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditDaftarNama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNama;
    private javax.swing.JButton btnNama1;
    private javax.swing.JButton btnNama2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelInpNama;
    private javax.swing.JLabel lbJmlNama;
    private javax.swing.JButton toGenerator;
    private javax.swing.JTextArea txaDaftarNama;
    private javax.swing.JTextField txfHapusSatu;
    private javax.swing.JTextField txfNama;
    // End of variables declaration//GEN-END:variables
}
