/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import java.sql.SQLException;
/**
 *
 * @author DELL
 */
public class Generator extends javax.swing.JFrame {

    ArrayList<String> dataNama = new ArrayList<>();
    ArrayList<String> dataNamaTeracak = new ArrayList<>();
    
    public int jmlAnggotaSaatAcak =0;
    public int nomorUrut;
    public String user = " ";
    /**
     * Creates new form TesPanel
     */
    public Generator() {
        initComponents();
    }

    public void acak(){
        dataNamaTeracak.removeAll(dataNamaTeracak);
        dataNamaTeracak.addAll(dataNama);
        Collections.shuffle(dataNamaTeracak);
    }

    public void jmlSatuGrup(){
        String ambilJml = txfJmlAnggotaTim.getText();
        if(txfJmlAnggotaTim.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Masukan jumlah orang dalam grup!");
        }else if (Integer.parseInt(ambilJml) > 0) {
            lbJmlAnggotaTim.setText(ambilJml);
            txfJmlAnggotaTim.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Input harus berupa angka lebih dari 0!");
        }
    }    

    public void pembagianGrup(){
        ArrayList<String> dataBagiBaru = new ArrayList<>();
        
        int no = 1;
        String ambilJml = lbJmlAnggotaTim.getText();
        lbJmlAnggotaTim.setText(ambilJml);
        
        txaHasilAcak.append(no + ").  ");
        for (int i = 0; i < dataNamaTeracak.size(); i++) {
            dataBagiBaru.add(dataNamaTeracak.get(i));
            txaHasilAcak.append(dataNamaTeracak.get(i));
            
            if(dataBagiBaru.size() > Integer.valueOf(ambilJml)-1){
                txaHasilAcak.append("\n");
                dataBagiBaru.removeAll(dataBagiBaru);

                if (i + 1 < dataNamaTeracak.size()) {
                        txaHasilAcak.append(no + 1 + ").  ");
                        no++;
                    }
                continue;    
            } 
            if (i + 1 != dataNamaTeracak.size()) {
                txaHasilAcak.append(" ~ ");
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        jPanel = new javax.swing.JPanel();
        btnJmlAnggotaTim = new javax.swing.JButton();
        lbJmlAnggotaTim = new javax.swing.JLabel();
        btnAcak = new javax.swing.JButton();
        btnHapusHasil = new javax.swing.JButton();
        labelInpNama = new javax.swing.JLabel();
        txfNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txfJmlAnggotaTim = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaHasilAcak = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jLabel3.setBackground(new java.awt.Color(255, 255, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Generator");

        kembali.setBackground(new java.awt.Color(255, 255, 0));
        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/output-onlinepngtools (4).png"))); // NOI18N
        kembali.setBorderPainted(false);
        kembali.setMaximumSize(new java.awt.Dimension(30, 30));
        kembali.setMinimumSize(new java.awt.Dimension(30, 30));
        kembali.setPreferredSize(new java.awt.Dimension(30, 30));
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kembali, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );

        jPanel.setBackground(new java.awt.Color(255, 204, 0));

        btnJmlAnggotaTim.setBackground(new java.awt.Color(255, 102, 0));
        btnJmlAnggotaTim.setText("Atur");
        btnJmlAnggotaTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJmlAnggotaTimActionPerformed(evt);
            }
        });

        lbJmlAnggotaTim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbJmlAnggotaTim.setText("0");

        btnAcak.setBackground(new java.awt.Color(255, 102, 0));
        btnAcak.setText("Acak Tim");
        btnAcak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcakActionPerformed(evt);
            }
        });

        btnHapusHasil.setBackground(new java.awt.Color(255, 102, 0));
        btnHapusHasil.setText("Hapus Hasil");
        btnHapusHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusHasilActionPerformed(evt);
            }
        });

        labelInpNama.setText("Nama Data Acak      ");

        txfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNamaActionPerformed(evt);
            }
        });

        jLabel4.setText("Jumlah Anggota Tiap Tim ");

        txfJmlAnggotaTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfJmlAnggotaTimActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(255, 102, 0));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHapusHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelLayout.createSequentialGroup()
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(labelInpNama))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txfNama, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                                .addComponent(txfJmlAnggotaTim, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnJmlAnggotaTim, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbJmlAnggotaTim, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                        .addGroup(jPanelLayout.createSequentialGroup()
                            .addComponent(btnAcak, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapusHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelInpNama)
                        .addComponent(txfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txfJmlAnggotaTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnJmlAnggotaTim)
                        .addComponent(lbJmlAnggotaTim))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnAcak, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        txaHasilAcak.setColumns(20);
        txaHasilAcak.setRows(5);
        jScrollPane2.setViewportView(txaHasilAcak);

        jLabel7.setText("Hasil");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(282, 282, 282)
                            .addComponent(jLabel7))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(640, 444));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (dataNamaTeracak.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Hasil pengacakan kosong, tidak dapat menyimpan!");
        }else if (txfNama.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap mengisi judul pengacakan terlebih dahulu");
        }else {
            try{
                String dataNamaTeracakString = String.join(",", dataNamaTeracak);
                String sql = "SELECT MAX(id_hasil) FROM hasil_acak";
                java.sql.Connection conn = (Connection)Config.configDB();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);
                res.next();
                int saveID = res.getInt(1)+1;

                sql = "SELECT MAX(urutan_hasil) FROM hasil_acak WHERE username = '" + user + "'";
                java.sql.Statement stmUrutanData = conn.createStatement();
                java.sql.ResultSet resUrutanData = stmUrutanData.executeQuery(sql);
                resUrutanData.next();
                int urutanSave = resUrutanData.getInt(1)+1;

                sql = "INSERT INTO hasil_acak VAlUES ('" + saveID + "','" + txfNama.getText() + "','" + dataNamaTeracakString + "','" + jmlAnggotaSaatAcak + "','" + urutanSave + "','" + user + "')";
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(null, "Proses Simpan Data Berhasil!");
            }catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusHasilActionPerformed
        if(txaHasilAcak.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Belum ada hasil group, Tidak bisa dihapus!");
        }else{
            dataNamaTeracak.removeAll(dataNamaTeracak);
            txaHasilAcak.setText("");
        }
    }//GEN-LAST:event_btnHapusHasilActionPerformed

    private void btnAcakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcakActionPerformed
        if(dataNama.isEmpty()){
            JOptionPane.showMessageDialog(this, "Masukan data nama terlebih dahulu!");
        }else if (lbJmlAnggotaTim.getText().equals("0")) {
            JOptionPane.showMessageDialog(this, "Jumlah anggota dalam satu tim tidak boleh 0!");
        }else{
            jmlAnggotaSaatAcak = Integer.parseInt(lbJmlAnggotaTim.getText());
            txaHasilAcak.setText("");
            acak();
            pembagianGrup();
        }
    }//GEN-LAST:event_btnAcakActionPerformed

    private void btnJmlAnggotaTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJmlAnggotaTimActionPerformed
        jmlSatuGrup();
    }//GEN-LAST:event_btnJmlAnggotaTimActionPerformed

    private void txfJmlAnggotaTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfJmlAnggotaTimActionPerformed
        jmlSatuGrup();
    }//GEN-LAST:event_txfJmlAnggotaTimActionPerformed

    private void txfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNamaActionPerformed
       
    }//GEN-LAST:event_txfNamaActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        EditDaftarNama e = new EditDaftarNama();
        e.dataNama.addAll(this.dataNama);
        e.user = this.user;
        e.tampilkanDariDB();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Generator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcak;
    private javax.swing.JButton btnHapusHasil;
    private javax.swing.JButton btnJmlAnggotaTim;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel labelInpNama;
    private javax.swing.JLabel lbJmlAnggotaTim;
    private javax.swing.JTextArea txaHasilAcak;
    private javax.swing.JTextField txfJmlAnggotaTim;
    private javax.swing.JTextField txfNama;
    // End of variables declaration//GEN-END:variables
}
